/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)BasicComponentDO.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.dataobject;

import com.github.javaclub.sword.domain.BaseDO;

/**
 * BasicComponentDO
 *
 * @version $Id: BasicComponentDO.java ${currentTime} Exp $
 */
public class BasicComponentDO extends BaseDO {

	private static final long serialVersionUID = 1621587400486L;
	
	/**
	 * 自增主键
	 */
	private Long id;

	private String widgetName;
	
	private Integer widgetType;

	private String widgetHtml;

	private String widgetFunction;

	private String widgetAjax;

	/**
	 * -1-不可用 0-开发调试中 1-可用
	 */
	private Integer status;

	/**
	 * 更新时间
	 */
	private java.util.Date gmtModified;

	/**
	 * 创建人
	 */
	private String creator;

	/**
	 * 修改人
	 */
	private String modifier;



	public BasicComponentDO() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getWidgetName() {
		return widgetName;
	}

	public void setWidgetName(String widgetName) {
		this.widgetName = widgetName;
	}

	public String getWidgetHtml() {
		return widgetHtml;
	}

	public void setWidgetHtml(String widgetHtml) {
		this.widgetHtml = widgetHtml;
	}

	public String getWidgetFunction() {
		return widgetFunction;
	}

	public void setWidgetFunction(String widgetFunction) {
		this.widgetFunction = widgetFunction;
	}

	public String getWidgetAjax() {
		return widgetAjax;
	}

	public void setWidgetAjax(String widgetAjax) {
		this.widgetAjax = widgetAjax;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public java.util.Date getGmtModified() {
		return gmtModified;
	}

	public void setGmtModified(java.util.Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	public String getCreator() {
		return creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getModifier() {
		return modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	public Integer getWidgetType() {
		return widgetType;
	}

	public void setWidgetType(Integer widgetType) {
		this.widgetType = widgetType;
	}

	
}

