/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)MenuModuleDO.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.dataobject;

import com.github.javaclub.sword.domain.BaseDO;

/**
 * MenuModuleDO
 *
 * @version $Id: MenuModuleDO.java ${currentTime} Exp $
 */
public class MenuModuleDO extends BaseDO {

	private static final long serialVersionUID = 1624952495755L;
	
	public static final int MENU_TYPE_DIR = 1;
	public static final int MENU_TYPE_PAGE = 2;
	public static final int MENU_TYPE_ACTION = 3;
	
	public static final String ATTR_RESID_PAGE = "pageResource";
	public static final String ATTR_RESID_MOUDLE = "bindResources";
	
	/**
	 * 自增主键
	 */
	private Long id;

	/**
	 * 名称
	 */
	private String name;

	/**
	 * 访问路径
	 */
	private String uri;

	/**
	 * 类型: 1-菜单目录 2-模块页面 3-功能点
	 */
	private Integer type;

	/**
	 * 父级ID
	 */
	private Long parentId;

	/**
	 * 图标/样式
	 */
	private String iconCss;

	/**
	 * 排序值
	 */
	private Integer sort;

	/**
	 * 备注
	 */
	private String remark;

	/**
	 * 创建人
	 */
	private String creator;

	/**
	 * 修改人
	 */
	private String modifier;



	public MenuModuleDO() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUri() {
		return uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Long getParentId() {
		return parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public String getIconCss() {
		return iconCss;
	}

	public void setIconCss(String iconCss) {
		this.iconCss = iconCss;
	}

	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getCreator() {
		return creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getModifier() {
		return modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}


	
}

