/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)MyTestDO.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.dataobject;

import com.github.javaclub.sword.domain.BaseDO;

/**
 * MyTestDO
 *
 * @version $Id: MyTestDO.java ${currentTime} Exp $
 */
public class MyTestDO extends BaseDO {

	private static final long serialVersionUID = 1622714475165L;
	
	/**
	 * 自增主键id
	 */
	private Long id;

	/**
	 * 用户名
	 */
	private String username;

	/**
	 * 手机号
	 */
	private String mobile;

	/**
	 * 邮件
	 */
	private String email;

	/**
	 * 密码
	 */
	private String password;

	/**
	 * 生日
	 */
	private java.util.Date birthday;

	/**
	 * 用户类型:1-普通 2-高级
	 */
	private Integer userType;

	/**
	 * 工号
	 */
	private String employeeNo;

	/**
	 * 呢称
	 */
	private String userNick;

	/**
	 * 真实姓名
	 */
	private String realName;

	/**
	 * 性别
	 */
	private Integer sex;

	/**
	 * 创建人
	 */
	private String creator;

	/**
	 * 修改人
	 */
	private String modifier;



	public MyTestDO() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public java.util.Date getBirthday() {
		return birthday;
	}

	public void setBirthday(java.util.Date birthday) {
		this.birthday = birthday;
	}

	public Integer getUserType() {
		return userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	public String getEmployeeNo() {
		return employeeNo;
	}

	public void setEmployeeNo(String employeeNo) {
		this.employeeNo = employeeNo;
	}

	public String getUserNick() {
		return userNick;
	}

	public void setUserNick(String userNick) {
		this.userNick = userNick;
	}

	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public Integer getSex() {
		return sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public String getCreator() {
		return creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getModifier() {
		return modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}


	
}

