/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)UserRoleDO.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.dataobject;

import com.github.javaclub.sword.domain.BaseDO;

/**
 * UserRoleDO
 *
 * @version $Id: UserRoleDO.java ${currentTime} Exp $
 */
public class UserRoleDO extends BaseDO {

	private static final long serialVersionUID = 1626188740695L;
	
	/**
	 * 主键id
	 */
	private Long id;

	/**
	 * 失效时间
	 */
	private java.util.Date expiredTime;

	/**
	 * 角色名称
	 */
	private Long userId;

	/**
	 * 角色代码标识
	 */
	private Long roleId;

	/**
	 * 创建人
	 */
	private String creator;

	/**
	 * 修改人
	 */
	private String modifier;



	public UserRoleDO() {
	}

	public UserRoleDO(Long userId, Long roleId) {
		this.userId = userId;
		this.roleId = roleId;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public java.util.Date getExpiredTime() {
		return expiredTime;
	}

	public void setExpiredTime(java.util.Date expiredTime) {
		this.expiredTime = expiredTime;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getRoleId() {
		return roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getCreator() {
		return creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getModifier() {
		return modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}
	
}

