/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)BlackWhiteListQuery.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.query;

import com.github.javaclub.sword.domain.DomainEntityQuery;

import java.util.Date;
import java.util.List;

/**
 * BlackWhiteListQuery
 *
 * @version $Id: BlackWhiteListQuery.java ${currentTime} Exp $
 */
public class BlackWhiteListQuery extends DomainEntityQuery {

	private static final long serialVersionUID = 1605152348075L;

	public static final String IDX_CREATETIME = "idx_create_time";
//	public static final String IDX_BIZCODE_CREATETIME = "idx_bizcode_createtime";

	/**
	 * 根据主键查询
	 */
	private Long id;

	/**
	 * 根据主键ID列表批量查询
	 */
	private List<Long> ids;

	/**
	 * 最小ID过滤条件
	 */
	private Long minId;

	/**
	 * 最大ID过滤条件
	 */
	private Long maxId;

	private String bizCode;
	private String identity;
	private Integer type;
	private Integer expireType;
	private String comment;
	private Integer isDeleted;
	private java.util.List<String> bizCodeInList;
	private java.util.List<String> identityInList;
	private java.util.List<Integer> typeInList;
	private java.util.List<Integer> expireTypeInList;
	private String creatorLike;
	private String modifierLike;

	/**
	 * 当前分页中最大的主键ID
	 */
	private Long maxPageId;
	private Date lastGmtCreate;

	private String forceIndex;

	public BlackWhiteListQuery() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public List<Long> getIds() {
		return ids;
	}

	public void setIds(List<Long> ids) {
		this.ids = ids;
	}

	public Long getMinId() {
		return minId;
	}

	public void setMinId(Long minId) {
		this.minId = minId;
	}

	public Long getMaxId() {
		return maxId;
	}

	public void setMaxId(Long maxId) {
		this.maxId = maxId;
	}

	public String getBizCode() {
		return this.bizCode;
	}

	public void setBizCode(String bizCode) {
		this.bizCode = bizCode;
	}

	public String getIdentity() {
		return this.identity;
	}

	public void setIdentity(String identity) {
		this.identity = identity;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getExpireType() {
		return this.expireType;
	}

	public void setExpireType(Integer expireType) {
		this.expireType = expireType;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	public java.util.List<String> getBizCodeInList() {
		return this.bizCodeInList;
	}

	public void setBizCodeInList(java.util.List<String> bizCodeInList) {
		this.bizCodeInList = bizCodeInList;
	}

	public java.util.List<String> getIdentityInList() {
		return this.identityInList;
	}

	public void setIdentityInList(java.util.List<String> identityInList) {
		this.identityInList = identityInList;
	}

	public java.util.List<Integer> getTypeInList() {
		return this.typeInList;
	}

	public void setTypeInList(java.util.List<Integer> typeInList) {
		this.typeInList = typeInList;
	}

	public java.util.List<Integer> getExpireTypeInList() {
		return this.expireTypeInList;
	}

	public void setExpireTypeInList(java.util.List<Integer> expireTypeInList) {
		this.expireTypeInList = expireTypeInList;
	}

	public String getCreatorLike() {
		return this.creatorLike;
	}

	public void setCreatorLike(String creatorLike) {
		this.creatorLike = creatorLike;
	}

	public String getModifierLike() {
		return this.modifierLike;
	}

	public void setModifierLike(String modifierLike) {
		this.modifierLike = modifierLike;
	}

	public Long getMaxPageId() {
		return maxPageId;
	}

	public void setMaxPageId(Long maxPageId) {
		this.maxPageId = maxPageId;
	}

	public Date getLastGmtCreate() {
		return lastGmtCreate;
	}

	public void setLastGmtCreate(Date lastGmtCreate) {
		this.lastGmtCreate = lastGmtCreate;
	}

	@Override
	public String getForceIndex() {
		return forceIndex;
	}

	@Override
	public void setForceIndex(String forceIndex) {
		this.forceIndex = forceIndex;
	}
}
