/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)LoginUserQuery.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.query;


import java.util.List;

import com.github.javaclub.sword.domain.DomainEntityQuery;

/**
 * LoginUserQuery
 *
 * @version $Id: LoginUserQuery.java ${currentTime} Exp $
 */
public class LoginUserQuery extends DomainEntityQuery {

	private static final long serialVersionUID = 1597496453266L;
	
	/**
	 * 根据主键查询 
	 */
	private Long id;
	
	/**
	 * 根据主键ID列表批量查询 
	 */
	private List<Long> ids; 
	
	/**
	 * 最小ID过滤条件 
	 */
	private Long minId;
	
	/**
	 * 最大ID过滤条件 
	 */
	private Long maxId;
	
	private String username;
	
	private String mobile;
	private String email;
	
	private String nameLike;
	
	private Integer status;

	public LoginUserQuery() {
	}
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public List<Long> getIds() {
		return ids;
	}

	public void setIds(List<Long> ids) {
		this.ids = ids;
	}
	
	public Long getMinId() {
		return minId;
	}

	public void setMinId(Long minId) {
		this.minId = minId;
	}
	
	public Long getMaxId() {
		return maxId;
	}

	public void setMaxId(Long maxId) {
		this.maxId = maxId;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getNameLike() {
		return nameLike;
	}

	public void setNameLike(String name) {
		this.nameLike = name;
	}
	
}

