/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)MyTestQuery.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.query;


import java.util.List;

import com.github.javaclub.sword.domain.DomainEntityQuery;

/**
 * MyTestQuery
 *
 * @version $Id: MyTestQuery.java ${currentTime} Exp $
 */
public class MyTestQuery extends DomainEntityQuery {

	private static final long serialVersionUID = 1622714475166L;
	
	/**
	 * 根据主键查询 
	 */
	private Long id;
	
	/**
	 * 根据主键ID列表批量查询 
	 */
	private List<Long> ids; 
	
	/**
	 * 最小ID过滤条件 
	 */
	private Long minId;
	
	/**
	 * 最大ID过滤条件 
	 */
	private Long maxId;
	
	private String username;
	private String mobile;
	private Integer sex;
	private java.util.List<Integer> userTypeInList;
	private java.util.List<String> employeeNoInList;
	private java.util.List<Integer> userTypeNotInList;
	private java.util.List<String> realNameNotInList;
	private String usernameLike;
	private String userNickNotLike;
	private String usernameNotLike;

	public MyTestQuery() {
	}
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public List<Long> getIds() {
		return ids;
	}

	public void setIds(List<Long> ids) {
		this.ids = ids;
	}
	
	public Long getMinId() {
		return minId;
	}

	public void setMinId(Long minId) {
		this.minId = minId;
	}
	
	public Long getMaxId() {
		return maxId;
	}

	public void setMaxId(Long maxId) {
		this.maxId = maxId;
	}
	
	public String getUsername() {
		return this.username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getMobile() {
		return this.mobile;
	}
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	public Integer getSex() {
		return this.sex;
	}
	public void setSex(Integer sex) {
		this.sex = sex;
	}
	public java.util.List<Integer> getUserTypeInList() {
		return this.userTypeInList;
	}
	public void setUserTypeInList(java.util.List<Integer> userTypeInList) {
		this.userTypeInList = userTypeInList;
	}
	public java.util.List<String> getEmployeeNoInList() {
		return this.employeeNoInList;
	}
	public void setEmployeeNoInList(java.util.List<String> employeeNoInList) {
		this.employeeNoInList = employeeNoInList;
	}
	public java.util.List<Integer> getUserTypeNotInList() {
		return this.userTypeNotInList;
	}
	public void setUserTypeNotInList(java.util.List<Integer> userTypeNotInList) {
		this.userTypeNotInList = userTypeNotInList;
	}
	public java.util.List<String> getRealNameNotInList() {
		return this.realNameNotInList;
	}
	public void setRealNameNotInList(java.util.List<String> realNameNotInList) {
		this.realNameNotInList = realNameNotInList;
	}
	public String getUsernameLike() {
		return this.usernameLike;
	}
	public void setUsernameLike(String usernameLike) {
		this.usernameLike = usernameLike;
	}
	public String getUserNickNotLike() {
		return this.userNickNotLike;
	}
	public void setUserNickNotLike(String userNickNotLike) {
		this.userNickNotLike = userNickNotLike;
	}
	public String getUsernameNotLike() {
		return this.usernameNotLike;
	}
	public void setUsernameNotLike(String usernameNotLike) {
		this.usernameNotLike = usernameNotLike;
	}
	
	
}

