/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)ResourceQuery.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.query;


import java.util.Arrays;
import java.util.List;

import com.github.javaclub.sword.core.Numbers;
import com.github.javaclub.sword.core.Strings;
import com.github.javaclub.sword.domain.DomainEntityQuery;

/**
 * ResourceQuery
 *
 * @version $Id: ResourceQuery.java ${currentTime} Exp $
 */
public class ResourceQuery extends DomainEntityQuery {

	private static final long serialVersionUID = 1624627240645L;
	
	/**
	 * 根据主键查询 
	 */
	private Long id;
	
	/**
	 * 根据主键ID列表批量查询 
	 */
	private List<Long> ids; 
	
	/**
	 * 最小ID过滤条件 
	 */
	private Long minId;
	
	/**
	 * 最大ID过滤条件 
	 */
	private Long maxId;
	
	private String idArray;
	
	private String uriLike;
	private String nameLike;
	private String codeLike;
	
	private Integer type;

	public ResourceQuery() {
	}
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public List<Long> getIds() {
		return ids;
	}

	public void setIds(List<Long> ids) {
		this.ids = ids;
	}
	
	public Long getMinId() {
		return minId;
	}

	public void setMinId(Long minId) {
		this.minId = minId;
	}
	
	public Long getMaxId() {
		return maxId;
	}

	public void setMaxId(Long maxId) {
		this.maxId = maxId;
	}
	
	public String getUriLike() {
		return this.uriLike;
	}
	public void setUriLike(String uriLike) {
		this.uriLike = uriLike;
	}
	public String getNameLike() {
		return this.nameLike;
	}
	public void setNameLike(String nameLike) {
		this.nameLike = nameLike;
	}
	public String getCodeLike() {
		return this.codeLike;
	}
	public void setCodeLike(String codeLike) {
		this.codeLike = codeLike;
	}

	public String getIdArray() {
		return idArray;
	}

	public void setIdArray(String idArray) {
		this.idArray = idArray;
	}
	
	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public void rebuildIds() {
		String[] arr = Strings.splitAndTrim(idArray, ",");
		if(null != arr && 0 < arr.length) {
			this.setIds(Numbers.toLongList(Arrays.asList(arr)));
		}
	}
	
}

