/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)RoleQuery.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.query;


import java.util.List;

import com.github.javaclub.sword.domain.DomainEntityQuery;

/**
 * RoleQuery
 *
 * @version $Id: RoleQuery.java ${currentTime} Exp $
 */
public class RoleQuery extends DomainEntityQuery {

	private static final long serialVersionUID = 1624867719636L;
	
	/**
	 * 根据主键查询 
	 */
	private Long id;
	
	/**
	 * 根据主键ID列表批量查询 
	 */
	private List<Long> ids; 
	
	/**
	 * 最小ID过滤条件 
	 */
	private Long minId;
	
	/**
	 * 最大ID过滤条件 
	 */
	private Long maxId;
	
	private Integer status;
	private String roleNameLike;
	
	/**
	 * role_code <> #{roleCodeNotEuqal} 
	 */
	private String roleCodeNotEuqal;

	public RoleQuery() {
	}
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public List<Long> getIds() {
		return ids;
	}

	public void setIds(List<Long> ids) {
		this.ids = ids;
	}
	
	public Long getMinId() {
		return minId;
	}

	public void setMinId(Long minId) {
		this.minId = minId;
	}
	
	public Long getMaxId() {
		return maxId;
	}

	public void setMaxId(Long maxId) {
		this.maxId = maxId;
	}
	
	public Integer getStatus() {
		return this.status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}
	public String getRoleNameLike() {
		return this.roleNameLike;
	}
	public void setRoleNameLike(String roleNameLike) {
		this.roleNameLike = roleNameLike;
	}

	public String getRoleCodeNotEuqal() {
		return roleCodeNotEuqal;
	}
	public void setRoleCodeNotEuqal(String roleCodeNotEuqal) {
		this.roleCodeNotEuqal = roleCodeNotEuqal;
	}
	
}

