/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)RoleUserQuery.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.query;


import com.github.javaclub.sword.domain.DomainEntityQuery;

import lombok.Data;

/**
 * RoleUserQuery
 *
 * @version $Id: RoleUserQuery.java ${currentTime} Exp $
 */
@Data
public class RoleUserQuery extends DomainEntityQuery {

	private static final long serialVersionUID = 1626188740696L;
	
	private Long userId;
	
	private Long roleId;
	
	/**
	 * 仅用于查询角色关联的用户时可用 
	 */
	private String username;
	
	/**
	 * 仅用于查询角色关联的用户时可用
	 */
	private String mobile;
	
	/**
	 * 仅用于查询角色关联的用户时可用
	 */
	private String nameLike;
	
	/**
	 * 仅用于查询用户关联的角色时可用 
	 */
	private String roleNameLike;
	
	public RoleUserQuery() {
	}

	public RoleUserQuery(int pageNo, int pageSize) {
		super(pageNo, pageSize);
	}
	
	
}

