/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)UserRoleQuery.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.query;


import java.util.List;

import com.github.javaclub.sword.domain.DomainEntityQuery;

/**
 * UserRoleQuery
 *
 * @version $Id: UserRoleQuery.java ${currentTime} Exp $
 */
public class UserRoleQuery extends DomainEntityQuery {

	private static final long serialVersionUID = 1626188740696L;
	
	/**
	 * 根据主键查询 
	 */
	private Long id;
	
	/**
	 * 根据主键ID列表批量查询 
	 */
	private List<Long> ids; 
	
	/**
	 * 最小ID过滤条件 
	 */
	private Long minId;
	
	/**
	 * 最大ID过滤条件 
	 */
	private Long maxId;
	
	private Long userId;
	private Long roleId;

	public UserRoleQuery() {
	}
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public List<Long> getIds() {
		return ids;
	}

	public void setIds(List<Long> ids) {
		this.ids = ids;
	}
	
	public Long getMinId() {
		return minId;
	}

	public void setMinId(Long minId) {
		this.minId = minId;
	}
	
	public Long getMaxId() {
		return maxId;
	}

	public void setMaxId(Long maxId) {
		this.maxId = maxId;
	}
	
	public Long getUserId() {
		return this.userId;
	}
	public void setUserId(Long userId) {
		this.userId = userId;
	}
	public Long getRoleId() {
		return this.roleId;
	}
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}
	
	
}

