/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)BasicComponentDAO.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.dao;

import com.github.javaclub.sword.domain.StandardDAO;
import ${packagePrefix}.dataobject.BasicComponentDO;

/**
 * BasicComponentDAO
 *
 * @version $Id: BasicComponentDAO.java ${currentTime} Exp $
 */
public interface BasicComponentDAO extends StandardDAO<BasicComponentDO, Long> {
	
	
	int changeStatus(BasicComponentDO bcd);
	
}
