/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)BlackWhiteListDAO.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.dao;

import com.github.javaclub.sword.domain.StandardDAO;
import ${packagePrefix}.dataobject.BlackWhiteListDO;

/**
 * BlackWhiteListDAO
 *
 * @version $Id: BlackWhiteListDAO.java ${currentTime} Exp $
 */
public interface BlackWhiteListDAO extends StandardDAO<BlackWhiteListDO, Long> {


    int deleteByExpire();
}
