/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)LoginUserDAO.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.dao;

import org.apache.ibatis.annotations.Param;

import com.github.javaclub.sword.domain.StandardDAO;
import ${packagePrefix}.dataobject.LoginUserDO;

/**
 * LoginUserDAO
 *
 * @version $Id: LoginUserDAO.java ${currentTime} Exp $
 */
public interface LoginUserDAO extends StandardDAO<LoginUserDO, Long> {

	LoginUserDO checkLogin(@Param("username") String username, @Param("password") String md5Pwd);

	int resetPassword(@Param("userid") Long userid, @Param("password") String md5Pwd);

	int resetSecondAuth(LoginUserDO loginUserDO);

	LoginUserDO matchUserByQueryKey(@Param("q") String q);
	
}

