/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)MyTestDAO.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.dao;

import com.github.javaclub.sword.domain.StandardDAO;
import ${packagePrefix}.dataobject.MyTestDO;

/**
 * MyTestDAO
 *
 * @version $Id: MyTestDAO.java ${currentTime} Exp $
 */
public interface MyTestDAO extends StandardDAO<MyTestDO, Long> {
	
	
	
}
