/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)ResourceDAO.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.github.javaclub.sword.domain.StandardDAO;
import ${packagePrefix}.dataobject.ResourceDO;

/**
 * ResourceDAO
 *
 * @version $Id: ResourceDAO.java ${currentTime} Exp $
 */
public interface ResourceDAO extends StandardDAO<ResourceDO, Long> {

	List<ResourceDO> queryRoleResourceList(@Param("roleIds") List<Long> roleIds);
	
}

