/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)RoleDAO.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.github.javaclub.sword.domain.StandardDAO;
import ${packagePrefix}.dataobject.RoleDO;

/**
 * RoleDAO
 *
 * @version $Id: RoleDAO.java ${currentTime} Exp $
 */
public interface RoleDAO extends StandardDAO<RoleDO, Long> {

	List<RoleDO> findUserRoleList(@Param("userId") Long userId);
	
}

