/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)RoleResourceDAO.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.dao;

import org.apache.ibatis.annotations.Param;

import com.github.javaclub.sword.domain.StandardDAO;
import ${packagePrefix}.dataobject.RoleResourceDO;

/**
 * RoleResourceDAO
 *
 * @version $Id: RoleResourceDAO.java ${currentTime} Exp $
 */
public interface RoleResourceDAO extends StandardDAO<RoleResourceDO, Long> {

	void deleteByRoleId(@Param("roleId") Long roleId);
	
}

