/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)BasicComponentServiceImpl.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.service.impl;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.github.javaclub.sword.core.BizObjects;
import ${packagePrefix}.dao.BasicComponentDAO;
import ${packagePrefix}.dataobject.BasicComponentDO;
import ${packagePrefix}.query.BasicComponentQuery;
import ${packagePrefix}.service.BasicComponentService;
import com.github.javaclub.sword.domain.QueryResult;
import com.github.javaclub.sword.domain.ResultDO;
import com.github.javaclub.sword.domain.dto.BatchOperationDTO;
import com.github.javaclub.sword.domain.enumtype.BasicMessage;
import com.google.common.collect.Lists;

/**
 * BasicComponentServiceImpl
 *
 * @version $Id: BasicComponentServiceImpl.java ${currentTime} Exp $
 */
@Service("basicComponentService")
public class BasicComponentServiceImpl implements BasicComponentService {
	
	static final Logger log = LoggerFactory.getLogger(BasicComponentServiceImpl.class);
	
	@Autowired
	private BasicComponentDAO basicComponentDAO;

	/**
	 * 创建时的业务校验
	 * 
	 * @param basicComponentDO 业务实体
	 */
	void doCreateCheck(BasicComponentDO basicComponentDO) {
		// TODO Auto-generated method stub
		
	}
	
	/**
	 * 更新时的业务校验
	 * 
	 * @param basicComponentDO 业务实体
	 */
	void doUpdateCheck(BasicComponentDO basicComponentDO) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public ResultDO<Boolean> save(BasicComponentDO basicComponentDO) {
		if(null == basicComponentDO.getId()) {
			return create(basicComponentDO);
		}
		BasicComponentDO db = basicComponentDAO.getById(basicComponentDO.getId());
		if(null == db) {
			return ResultDO.failure(BasicMessage.NOT_FOUND);
		}
		return update(basicComponentDO);
	}

	@Override
	public ResultDO<Boolean> create(BasicComponentDO basicComponentDO) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			this.doCreateCheck(basicComponentDO);
			int num = basicComponentDAO.insert(basicComponentDO);
			result = ResultDO.result(num > 0, "创建记录失败");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public BatchOperationDTO<BasicComponentDO> createBatch(List<BasicComponentDO> list) {
		BatchOperationDTO<BasicComponentDO> bod = new BatchOperationDTO<BasicComponentDO>();
		List<BasicComponentDO> toAdd = Lists.newArrayList();
		for (BasicComponentDO item : list) {
			try {
				this.doCreateCheck(item);
			} catch (Exception e) {
				bod.addFailure(item);
				continue;
			}
			toAdd.add(item);
		}
		
		try {
			if(toAdd.size() > 0) {
				basicComponentDAO.insertBatch(toAdd);
				bod.setSuccessList(toAdd);
			}
		} catch (Exception e) {
			bod.setMessage(e.getMessage());
			log.error("BasicComponentService createBatch", e);
		}
		
		return bod;
	}

	@Override
	public ResultDO<Boolean> update(BasicComponentDO basicComponentDO) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			BizObjects.requireNotNull(basicComponentDO.getId(), "主键ID不能为空");
			this.doUpdateCheck(basicComponentDO);
			int num = basicComponentDAO.update(basicComponentDO);
			result = ResultDO.result(num > 0, "没有记录被更新");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public ResultDO<Boolean> deleteById(Long id) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			int num = basicComponentDAO.deleteById(id);
			result = ResultDO.result(num > 0, "没有记录被删除");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public ResultDO<BasicComponentDO> getById(Long id) {
		ResultDO<BasicComponentDO> result = ResultDO.failure();
		try {
			BasicComponentDO dbRecord = basicComponentDAO.getById(id);
			if(null != dbRecord) {
				result = ResultDO.success(dbRecord);
			}
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		
		return result;
	}
	
	@Override
	public BasicComponentDO selectById(Long id) {
		return basicComponentDAO.getById(id);
	}
	
	@Override
	public BasicComponentDO selectOne(BasicComponentQuery query) {
		List<BasicComponentDO> list = basicComponentDAO.queryList(query);
		if(null != list && list.size() > 0) {
			return list.get(0);
		}
		return null;
	}

	@Override
	public int count(BasicComponentQuery query) {
		return basicComponentDAO.count(query);
	}

	@Override
	public List<BasicComponentDO> findList(BasicComponentQuery query) {
		return basicComponentDAO.queryList(query);
	}

	@Override
	public QueryResult<BasicComponentDO> findListWithCount(BasicComponentQuery query) {
		QueryResult<BasicComponentDO> queryResult = new QueryResult<BasicComponentDO>();
		try {
			List<BasicComponentDO> list = basicComponentDAO.queryList(query);
			int count = basicComponentDAO.count(query);
			queryResult.setTotalCount(count);
			queryResult.setEntry(list);
			queryResult.setSuccess(true);
		} catch (Exception e) {
			log.error("", e);
			queryResult.setSuccess(false);
			queryResult.setMessage(e.getMessage());
		}
		return queryResult;
	}

	@Override
	public boolean changeStatus(BasicComponentDO bcd) {
		BizObjects.requireNotNull(bcd, "实体对象内容不能为空");
		BizObjects.requireNotNullGtZero(bcd.getId(), "主键ID不能为空");
		BizObjects.requireNotNull(bcd.getStatus(), "状态值不能为空");
		return basicComponentDAO.changeStatus(bcd) > 0;
	}
	
	

}
