/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)BwlEnumServiceImpl.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.service.impl;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.github.javaclub.sword.core.BizObjects;
import com.github.javaclub.sword.domain.QueryResult;
import com.github.javaclub.sword.domain.ResultDO;
import com.github.javaclub.sword.domain.dto.BatchOperationDTO;
import com.github.javaclub.sword.domain.enumtype.BasicMessage;
import com.google.common.collect.Lists;
import ${packagePrefix}.dao.BwlEnumDAO;
import ${packagePrefix}.dataobject.BwlEnumDO;
import ${packagePrefix}.query.BwlEnumQuery;
import ${packagePrefix}.service.BwlEnumService;

/**
 * BwlEnumServiceImpl
 *
 * @version $Id: BwlEnumServiceImpl.java ${currentTime} Exp $
 */
@Service("bwlEnumService")
public class BwlEnumServiceImpl implements BwlEnumService {
	
	static final Logger log = LoggerFactory.getLogger(BwlEnumServiceImpl.class);
	
	@Autowired
	private BwlEnumDAO BwlEnumDAO;

	/**
	 * 创建时的业务校验
	 * 
	 * @param BwlEnumDO 业务实体
	 */
	void doCreateCheck(BwlEnumDO BwlEnumDO) {
		// TODO Auto-generated method stub
		
	}
	
	/**
	 * 更新时的业务校验
	 * 
	 * @param BwlEnumDO 业务实体
	 */
	void doUpdateCheck(BwlEnumDO BwlEnumDO) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public ResultDO<Boolean> save(BwlEnumDO BwlEnumDO) {
		if(null == BwlEnumDO.getId()) {
			return create(BwlEnumDO);
		}
		BwlEnumDO db = BwlEnumDAO.getById(BwlEnumDO.getId());
		if(null == db) {
			return ResultDO.failure(BasicMessage.NOT_FOUND);
		}
		return update(BwlEnumDO);
	}

	@Override
	public ResultDO<Boolean> create(BwlEnumDO BwlEnumDO) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			this.doCreateCheck(BwlEnumDO);
			int num = BwlEnumDAO.insert(BwlEnumDO);
			result = ResultDO.result(num > 0, "创建记录失败");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public ResultDO<Integer> createReturnId(BwlEnumDO BwlEnumDO) {
		ResultDO<Integer> result = ResultDO.failure();
		try {
			this.doCreateCheck(BwlEnumDO);
			int num = BwlEnumDAO.insert(BwlEnumDO);
			if (num > 0) {
				result = ResultDO.success();
				result.setEntry(BwlEnumDO.getId());
				return result;
			}
			result.setMessage("创建记录失败");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public BatchOperationDTO<BwlEnumDO> createBatch(List<BwlEnumDO> list) {
		BatchOperationDTO<BwlEnumDO> bod = new BatchOperationDTO<BwlEnumDO>();
		List<BwlEnumDO> toAdd = Lists.newArrayList();
		for (BwlEnumDO item : list) {
			try {
				this.doCreateCheck(item);
			} catch (Exception e) {
				bod.addFailure(item);
				continue;
			}
			toAdd.add(item);
		}
		
		try {
			if(toAdd.size() > 0) {
				BwlEnumDAO.insertBatch(toAdd);
				bod.setSuccessList(toAdd);
			}
		} catch (Exception e) {
			bod.setMessage(e.getMessage());
			log.error("BWBizEnumsService createBatch", e);
		}
		
		return bod;
	}

	@Override
	public ResultDO<Boolean> update(BwlEnumDO BwlEnumDO) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			BizObjects.requireNotNull(BwlEnumDO.getId(), "主键ID不能为空");
			this.doUpdateCheck(BwlEnumDO);
			int num = BwlEnumDAO.update(BwlEnumDO);
			result = ResultDO.result(num > 0, "没有记录被更新");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public ResultDO<Boolean> deleteById(Integer id) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			int num = BwlEnumDAO.deleteById(id);
			result = ResultDO.result(num > 0, "没有记录被删除");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public ResultDO<BwlEnumDO> getById(Integer id) {
		ResultDO<BwlEnumDO> result = ResultDO.failure();
		try {
			BwlEnumDO dbRecord = BwlEnumDAO.getById(id);
			if(null != dbRecord) {
				result = ResultDO.success(dbRecord);
			}
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		
		return result;
	}
	
	@Override
	public BwlEnumDO selectById(Integer id) {
		return BwlEnumDAO.getById(id);
	}
	
	@Override
	public BwlEnumDO selectOne(BwlEnumQuery query) {
		List<BwlEnumDO> list = BwlEnumDAO.queryList(query);
		if(null != list && list.size() > 0) {
			return list.get(0);
		}
		return null;
	}

	@Override
	public int count(BwlEnumQuery query) {
		return BwlEnumDAO.count(query);
	}

	@Override
	public List<BwlEnumDO> findList(BwlEnumQuery query) {
		return BwlEnumDAO.queryList(query);
	}

	@Override
	public QueryResult<BwlEnumDO> findListWithCount(BwlEnumQuery query) {
		QueryResult<BwlEnumDO> queryResult = new QueryResult<BwlEnumDO>();
		try {
			List<BwlEnumDO> list = BwlEnumDAO.queryList(query);
			int count = BwlEnumDAO.count(query);
			queryResult.setTotalCount(count);
			queryResult.setEntry(list);
			queryResult.setSuccess(true);
		} catch (Exception e) {
			log.error("", e);
			queryResult.setSuccess(false);
			queryResult.setMessage(e.getMessage());
		}
		return queryResult;
	}

}
