/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)MyTestServiceImpl.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.service.impl;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.github.javaclub.sword.core.BizObjects;
import ${packagePrefix}.dao.MyTestDAO;
import ${packagePrefix}.dataobject.MyTestDO;
import ${packagePrefix}.query.MyTestQuery;
import ${packagePrefix}.service.MyTestService;
import com.github.javaclub.sword.domain.QueryResult;
import com.github.javaclub.sword.domain.ResultDO;
import com.github.javaclub.sword.domain.dto.BatchOperationDTO;
import com.github.javaclub.sword.domain.enumtype.BasicMessage;
import com.google.common.collect.Lists;

/**
 * MyTestServiceImpl
 *
 * @version $Id: MyTestServiceImpl.java ${currentTime} Exp $
 */
@Service("myTestService")
public class MyTestServiceImpl implements MyTestService {
	
	static final Logger log = LoggerFactory.getLogger(MyTestServiceImpl.class);
	
	@Autowired
	private MyTestDAO myTestDAO;

	/**
	 * 创建时的业务校验
	 * 
	 * @param myTestDO 业务实体
	 */
	void doCreateCheck(MyTestDO myTestDO) {
		// TODO Auto-generated method stub
		
	}
	
	/**
	 * 更新时的业务校验
	 * 
	 * @param myTestDO 业务实体
	 */
	void doUpdateCheck(MyTestDO myTestDO) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public ResultDO<Boolean> save(MyTestDO myTestDO) {
		if(null == myTestDO.getId()) {
			return create(myTestDO);
		}
		MyTestDO db = myTestDAO.getById(myTestDO.getId());
		if(null == db) {
			return ResultDO.failure(BasicMessage.NOT_FOUND);
		}
		return update(myTestDO);
	}

	@Override
	public ResultDO<Boolean> create(MyTestDO myTestDO) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			this.doCreateCheck(myTestDO);
			int num = myTestDAO.insert(myTestDO);
			result = ResultDO.result(num > 0, "创建记录失败");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public BatchOperationDTO<MyTestDO> createBatch(List<MyTestDO> list) {
		BatchOperationDTO<MyTestDO> bod = new BatchOperationDTO<MyTestDO>();
		List<MyTestDO> toAdd = Lists.newArrayList();
		for (MyTestDO item : list) {
			try {
				this.doCreateCheck(item);
			} catch (Exception e) {
				bod.addFailure(item);
				continue;
			}
			toAdd.add(item);
		}
		
		try {
			if(toAdd.size() > 0) {
				myTestDAO.insertBatch(toAdd);
				bod.setSuccessList(toAdd);
			}
		} catch (Exception e) {
			bod.setMessage(e.getMessage());
			log.error("MyTestService createBatch", e);
		}
		
		return bod;
	}

	@Override
	public ResultDO<Boolean> update(MyTestDO myTestDO) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			BizObjects.requireNotNull(myTestDO.getId(), "主键ID不能为空");
			this.doUpdateCheck(myTestDO);
			int num = myTestDAO.update(myTestDO);
			result = ResultDO.result(num > 0, "没有记录被更新");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public ResultDO<Boolean> deleteById(Long id) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			int num = myTestDAO.deleteById(id);
			result = ResultDO.result(num > 0, "没有记录被删除");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public ResultDO<MyTestDO> getById(Long id) {
		ResultDO<MyTestDO> result = ResultDO.failure();
		try {
			MyTestDO dbRecord = myTestDAO.getById(id);
			if(null != dbRecord) {
				result = ResultDO.success(dbRecord);
			}
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		
		return result;
	}
	
	@Override
	public MyTestDO selectById(Long id) {
		return myTestDAO.getById(id);
	}
	
	@Override
	public MyTestDO selectOne(MyTestQuery query) {
		List<MyTestDO> list = myTestDAO.queryList(query);
		if(null != list && list.size() > 0) {
			return list.get(0);
		}
		return null;
	}

	@Override
	public int count(MyTestQuery query) {
		return myTestDAO.count(query);
	}

	@Override
	public List<MyTestDO> findList(MyTestQuery query) {
		return myTestDAO.queryList(query);
	}

	@Override
	public QueryResult<MyTestDO> findListWithCount(MyTestQuery query) {
		QueryResult<MyTestDO> queryResult = new QueryResult<MyTestDO>();
		try {
			List<MyTestDO> list = myTestDAO.queryList(query);
			int count = myTestDAO.count(query);
			queryResult.setTotalCount(count);
			queryResult.setEntry(list);
			queryResult.setSuccess(true);
		} catch (Exception e) {
			log.error("", e);
			queryResult.setSuccess(false);
			queryResult.setMessage(e.getMessage());
		}
		return queryResult;
	}

}
