/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)RoleMenuServiceImpl.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.service.impl;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.github.javaclub.sword.core.BizObjects;
import ${packagePrefix}.dao.RoleMenuDAO;
import ${packagePrefix}.dataobject.RoleMenuDO;
import ${packagePrefix}.query.RoleMenuQuery;
import ${packagePrefix}.service.RoleMenuService;
import com.github.javaclub.sword.domain.QueryResult;
import com.github.javaclub.sword.domain.ResultDO;
import com.github.javaclub.sword.domain.dto.BatchOperationDTO;
import com.github.javaclub.sword.domain.enumtype.BasicMessage;
import com.google.common.collect.Lists;

/**
 * RoleMenuServiceImpl
 *
 * @version $Id: RoleMenuServiceImpl.java ${currentTime} Exp $
 */
@Service("roleMenuService")
public class RoleMenuServiceImpl implements RoleMenuService {
	
	static final Logger log = LoggerFactory.getLogger(RoleMenuServiceImpl.class);
	
	@Autowired
	private RoleMenuDAO roleMenuDAO;

	/**
	 * 创建时的业务校验
	 * 
	 * @param roleMenuDO 业务实体
	 */
	void doCreateCheck(RoleMenuDO roleMenuDO) {
		// TODO Auto-generated method stub
		
	}
	
	/**
	 * 更新时的业务校验
	 * 
	 * @param roleMenuDO 业务实体
	 */
	void doUpdateCheck(RoleMenuDO roleMenuDO) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public ResultDO<Boolean> save(RoleMenuDO roleMenuDO) {
		if(null == roleMenuDO.getId()) {
			return create(roleMenuDO);
		}
		RoleMenuDO db = roleMenuDAO.getById(roleMenuDO.getId());
		if(null == db) {
			return ResultDO.failure(BasicMessage.NOT_FOUND);
		}
		return update(roleMenuDO);
	}

	@Override
	public ResultDO<Boolean> create(RoleMenuDO roleMenuDO) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			this.doCreateCheck(roleMenuDO);
			int num = roleMenuDAO.insert(roleMenuDO);
			result = ResultDO.result(num > 0, "创建记录失败");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public BatchOperationDTO<RoleMenuDO> createBatch(List<RoleMenuDO> list) {
		BatchOperationDTO<RoleMenuDO> bod = new BatchOperationDTO<RoleMenuDO>();
		List<RoleMenuDO> toAdd = Lists.newArrayList();
		for (RoleMenuDO item : list) {
			try {
				this.doCreateCheck(item);
			} catch (Exception e) {
				bod.addFailure(item);
				continue;
			}
			toAdd.add(item);
		}
		
		try {
			if(toAdd.size() > 0) {
				roleMenuDAO.insertBatch(toAdd);
				bod.setSuccessList(toAdd);
			}
		} catch (Exception e) {
			bod.setMessage(e.getMessage());
			log.error("RoleMenuService createBatch", e);
		}
		
		return bod;
	}

	@Override
	public ResultDO<Boolean> update(RoleMenuDO roleMenuDO) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			BizObjects.requireNotNull(roleMenuDO.getId(), "主键ID不能为空");
			this.doUpdateCheck(roleMenuDO);
			int num = roleMenuDAO.update(roleMenuDO);
			result = ResultDO.result(num > 0, "没有记录被更新");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public ResultDO<Boolean> deleteById(Long id) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			int num = roleMenuDAO.deleteById(id);
			result = ResultDO.result(num > 0, "没有记录被删除");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public ResultDO<RoleMenuDO> getById(Long id) {
		ResultDO<RoleMenuDO> result = ResultDO.failure();
		try {
			RoleMenuDO dbRecord = roleMenuDAO.getById(id);
			if(null != dbRecord) {
				result = ResultDO.success(dbRecord);
			}
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		
		return result;
	}
	
	@Override
	public RoleMenuDO selectById(Long id) {
		return roleMenuDAO.getById(id);
	}
	
	@Override
	public RoleMenuDO selectOne(RoleMenuQuery query) {
		List<RoleMenuDO> list = roleMenuDAO.queryList(query);
		if(null != list && list.size() > 0) {
			return list.get(0);
		}
		return null;
	}
	

	@Override
	public List<Long> findRoleMenuNode(Long roleId) {
		return roleMenuDAO.findRoleMenuNode(roleId);
	}

	@Override
	public int count(RoleMenuQuery query) {
		return roleMenuDAO.count(query);
	}

	@Override
	public List<RoleMenuDO> findList(RoleMenuQuery query) {
		return roleMenuDAO.queryList(query);
	}

	@Override
	public QueryResult<RoleMenuDO> findListWithCount(RoleMenuQuery query) {
		QueryResult<RoleMenuDO> queryResult = new QueryResult<RoleMenuDO>();
		try {
			List<RoleMenuDO> list = roleMenuDAO.queryList(query);
			int count = roleMenuDAO.count(query);
			queryResult.setTotalCount(count);
			queryResult.setEntry(list);
			queryResult.setSuccess(true);
		} catch (Exception e) {
			log.error("", e);
			queryResult.setSuccess(false);
			queryResult.setMessage(e.getMessage());
		}
		return queryResult;
	}

}
