/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)UserRoleServiceImpl.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.service.impl;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.github.javaclub.sword.core.BizObjects;
import ${packagePrefix}.dao.UserRoleDAO;
import ${packagePrefix}.dataobject.UserRoleDO;
import ${packagePrefix}.query.UserRoleQuery;
import ${packagePrefix}.service.UserRoleService;
import com.github.javaclub.sword.domain.QueryResult;
import com.github.javaclub.sword.domain.ResultDO;
import com.github.javaclub.sword.domain.dto.BatchOperationDTO;
import com.github.javaclub.sword.domain.enumtype.BasicMessage;
import com.google.common.collect.Lists;

/**
 * UserRoleServiceImpl
 *
 * @version $Id: UserRoleServiceImpl.java ${currentTime} Exp $
 */
@Service("userRoleService")
public class UserRoleServiceImpl implements UserRoleService {
	
	static final Logger log = LoggerFactory.getLogger(UserRoleServiceImpl.class);
	
	@Autowired
	private UserRoleDAO userRoleDAO;

	/**
	 * 创建时的业务校验
	 * 
	 * @param userRoleDO 业务实体
	 */
	void doCreateCheck(UserRoleDO userRoleDO) {
		// TODO Auto-generated method stub
		
	}
	
	/**
	 * 更新时的业务校验
	 * 
	 * @param userRoleDO 业务实体
	 */
	void doUpdateCheck(UserRoleDO userRoleDO) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public ResultDO<Boolean> save(UserRoleDO userRoleDO) {
		if(null == userRoleDO.getId()) {
			return create(userRoleDO);
		}
		UserRoleDO db = userRoleDAO.getById(userRoleDO.getId());
		if(null == db) {
			return ResultDO.failure(BasicMessage.NOT_FOUND);
		}
		return update(userRoleDO);
	}

	@Override
	public ResultDO<Boolean> create(UserRoleDO userRoleDO) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			this.doCreateCheck(userRoleDO);
			int num = userRoleDAO.insert(userRoleDO);
			result = ResultDO.result(num > 0, "创建记录失败");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public BatchOperationDTO<UserRoleDO> createBatch(List<UserRoleDO> list) {
		BatchOperationDTO<UserRoleDO> bod = new BatchOperationDTO<UserRoleDO>();
		List<UserRoleDO> toAdd = Lists.newArrayList();
		for (UserRoleDO item : list) {
			try {
				this.doCreateCheck(item);
			} catch (Exception e) {
				bod.addFailure(item);
				continue;
			}
			toAdd.add(item);
		}
		
		try {
			if(toAdd.size() > 0) {
				userRoleDAO.insertBatch(toAdd);
				bod.setSuccessList(toAdd);
			}
		} catch (Exception e) {
			bod.setMessage(e.getMessage());
			log.error("UserRoleService createBatch", e);
		}
		
		return bod;
	}

	@Override
	public ResultDO<Boolean> update(UserRoleDO userRoleDO) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			BizObjects.requireNotNull(userRoleDO.getId(), "主键ID不能为空");
			this.doUpdateCheck(userRoleDO);
			int num = userRoleDAO.update(userRoleDO);
			result = ResultDO.result(num > 0, "没有记录被更新");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public ResultDO<Boolean> deleteById(Long id) {
		ResultDO<Boolean> result = ResultDO.failure();
		try {
			int num = userRoleDAO.deleteById(id);
			result = ResultDO.result(num > 0, "没有记录被删除");
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		return result;
	}

	@Override
	public ResultDO<UserRoleDO> getById(Long id) {
		ResultDO<UserRoleDO> result = ResultDO.failure();
		try {
			UserRoleDO dbRecord = userRoleDAO.getById(id);
			if(null != dbRecord) {
				result = ResultDO.success(dbRecord);
			}
		} catch (Exception e) {
			log.error("", e);
			result.setMessage(e.getMessage());
		}
		
		return result;
	}
	
	@Override
	public UserRoleDO selectById(Long id) {
		return userRoleDAO.getById(id);
	}
	
	@Override
	public UserRoleDO selectOne(UserRoleQuery query) {
		List<UserRoleDO> list = userRoleDAO.queryList(query);
		if(null != list && list.size() > 0) {
			return list.get(0);
		}
		return null;
	}

	@Override
	public int count(UserRoleQuery query) {
		return userRoleDAO.count(query);
	}

	@Override
	public List<UserRoleDO> findList(UserRoleQuery query) {
		return userRoleDAO.queryList(query);
	}

	@Override
	public QueryResult<UserRoleDO> findListWithCount(UserRoleQuery query) {
		QueryResult<UserRoleDO> queryResult = new QueryResult<UserRoleDO>();
		try {
			List<UserRoleDO> list = userRoleDAO.queryList(query);
			int count = userRoleDAO.count(query);
			queryResult.setTotalCount(count);
			queryResult.setEntry(list);
			queryResult.setSuccess(true);
		} catch (Exception e) {
			log.error("", e);
			queryResult.setSuccess(false);
			queryResult.setMessage(e.getMessage());
		}
		return queryResult;
	}

}
