/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)BasicComponentService.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.service;

import java.util.List;

import ${packagePrefix}.dataobject.BasicComponentDO;
import ${packagePrefix}.query.BasicComponentQuery;
import com.github.javaclub.sword.domain.QueryResult;
import com.github.javaclub.sword.domain.ResultDO;
import com.github.javaclub.sword.domain.dto.BatchOperationDTO;

/**
 * BasicComponentService
 *
 * @version $Id: BasicComponentService.java ${currentTime} Exp $
 */
public interface BasicComponentService {

	/**
	 * 创建或更新业务实体（BasicComponentDO）
	 * 
	 * @param basicComponentDO 业务实体
	 * @return 操作结果
	 */
	ResultDO<Boolean> save(BasicComponentDO basicComponentDO);

	/**
	 * 创建业务实体（BasicComponentDO）
	 * 
	 * @param basicComponentDO 业务实体
	 * @return 创建结果
	 */
	ResultDO<Boolean> create(BasicComponentDO basicComponentDO);
	
	/**
	 * 批量创建业务实体（BasicComponentDO）
	 * 
	 * @param list 业务实体列表集合
	 * @return 批量处理结果
	 */
	BatchOperationDTO<BasicComponentDO> createBatch(List<BasicComponentDO> list);
	
	/**
	 * 更新业务实体（BasicComponentDO）
	 * 
	 * @param basicComponentDO 业务实体
	 * @return 更新结果
	 */
	ResultDO<Boolean> update(BasicComponentDO basicComponentDO);
	
	/**
	 * 根据主键删除单个业务实体（BasicComponentDO）
	 * 
	 * @param id 业务实体的主键ID
	 * @return 删除结果
	 */
	ResultDO<Boolean> deleteById(Long id);
	
	/**
	 * 根据主键查询单个业务实体（BasicComponentDO）
	 * 
	 * @param id 业务实体的主键ID
	 * @return 查询结果
	 */
	ResultDO<BasicComponentDO> getById(Long id);
	
	BasicComponentDO selectById(Long id);
	
	BasicComponentDO selectOne(BasicComponentQuery query);

	/**
	 * 根据一组查询条件统计总数
	 * 
	 * @param query 查询条件
	 * @return 满足查询条件的记录总数
	 */
	int count(BasicComponentQuery query);
	
	/**
	 * 根据一组查询条件查询业务实体列表
	 * 
	 * @param query 查询条件
	 * @return 业务实体列表集合
	 */
	List<BasicComponentDO> findList(BasicComponentQuery query);
	
	/**
	 * 根据一组查询条件查询业务实体列表，同时返回总记录数
	 * 
	 * @param query 查询条件
	 * @return 查询结果（含总记录数）
	 */
	QueryResult<BasicComponentDO> findListWithCount(BasicComponentQuery query);
	
	boolean changeStatus(BasicComponentDO bcd);
}
