/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)BlackWhiteListService.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.service;

import java.util.List;

import com.github.javaclub.sword.domain.QueryResult;
import com.github.javaclub.sword.domain.ResultDO;
import com.github.javaclub.sword.domain.dto.BatchOperationDTO;
import ${packagePrefix}.dataobject.BlackWhiteListDO;
import ${packagePrefix}.query.BlackWhiteListQuery;

/**
 * BlackWhiteListService
 *
 * @version $Id: BlackWhiteListService.java ${currentTime} Exp $
 */
public interface BlackWhiteListService {

	/**
	 * 创建或更新业务实体（BlackWhiteListDO）
	 * 
	 * @param blackWhiteListDO 业务实体
	 * @return 操作结果
	 */
	ResultDO<Boolean> save(BlackWhiteListDO blackWhiteListDO);

	/**
	 * 创建业务实体（BlackWhiteListDO）
	 * 
	 * @param blackWhiteListDO 业务实体
	 * @return 创建结果
	 */
	ResultDO<Boolean> create(BlackWhiteListDO blackWhiteListDO);

	ResultDO<Long> createReturnId(BlackWhiteListDO blackWhiteListDO);
	
	/**
	 * 批量创建业务实体（BlackWhiteListDO）
	 * 
	 * @param list 业务实体列表集合
	 * @return 批量处理结果
	 */
	BatchOperationDTO<BlackWhiteListDO> createBatch(List<BlackWhiteListDO> list);
	
	/**
	 * 更新业务实体（BlackWhiteListDO）
	 * 
	 * @param blackWhiteListDO 业务实体
	 * @return 更新结果
	 */
	ResultDO<Boolean> update(BlackWhiteListDO blackWhiteListDO);
	
	/**
	 * 根据主键删除单个业务实体（BlackWhiteListDO）
	 * 
	 * @param id 业务实体的主键ID
	 * @return 删除结果
	 */
	ResultDO<Boolean> deleteById(Long id);
	
	/**
	 * 根据主键查询单个业务实体（BlackWhiteListDO）
	 * 
	 * @param id 业务实体的主键ID
	 * @return 查询结果
	 */
	ResultDO<BlackWhiteListDO> getById(Long id);
	
	BlackWhiteListDO selectById(Long id);
	
	BlackWhiteListDO selectOne(BlackWhiteListQuery query);

	/**
	 * 根据一组查询条件统计总数
	 * 
	 * @param query 查询条件
	 * @return 满足查询条件的记录总数
	 */
	int count(BlackWhiteListQuery query);
	
	/**
	 * 根据一组查询条件查询业务实体列表
	 * 
	 * @param query 查询条件
	 * @return 业务实体列表集合
	 */
	List<BlackWhiteListDO> findList(BlackWhiteListQuery query);
	
	/**
	 * 根据一组查询条件查询业务实体列表，同时返回总记录数
	 * 
	 * @param query 查询条件
	 * @return 查询结果（含总记录数）
	 */
	QueryResult<BlackWhiteListDO> findListWithCount(BlackWhiteListQuery query);

	/**
	 * 删除过期的名单
	 * @return
	 */
	int deleteByExpire();

}
