/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)BWBizEnumsService.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.service;

import java.util.List;

import com.github.javaclub.sword.domain.QueryResult;
import com.github.javaclub.sword.domain.ResultDO;
import com.github.javaclub.sword.domain.dto.BatchOperationDTO;
import ${packagePrefix}.dataobject.BwlEnumDO;
import ${packagePrefix}.query.BwlEnumQuery;

/**
 * BWBizEnumsService
 *
 * @version $Id: BWBizEnumsService.java ${currentTime} Exp $
 */
public interface BwlEnumService {

	/**
	 * 创建或更新业务实体（BwlEnumDO）
	 * 
	 * @param BwlEnumDO 业务实体
	 * @return 操作结果
	 */
	ResultDO<Boolean> save(BwlEnumDO BwlEnumDO);

	/**
	 * 创建业务实体（BwlEnumDO）
	 * 
	 * @param BwlEnumDO 业务实体
	 * @return 创建结果
	 */
	ResultDO<Boolean> create(BwlEnumDO BwlEnumDO);

	ResultDO<Integer> createReturnId(BwlEnumDO BwlEnumDO);
	
	/**
	 * 批量创建业务实体（BwlEnumDO）
	 * 
	 * @param list 业务实体列表集合
	 * @return 批量处理结果
	 */
	BatchOperationDTO<BwlEnumDO> createBatch(List<BwlEnumDO> list);
	
	/**
	 * 更新业务实体（BwlEnumDO）
	 * 
	 * @param BwlEnumDO 业务实体
	 * @return 更新结果
	 */
	ResultDO<Boolean> update(BwlEnumDO BwlEnumDO);
	
	/**
	 * 根据主键删除单个业务实体（BwlEnumDO）
	 * 
	 * @param id 业务实体的主键ID
	 * @return 删除结果
	 */
	ResultDO<Boolean> deleteById(Integer id);
	
	/**
	 * 根据主键查询单个业务实体（BwlEnumDO）
	 * 
	 * @param id 业务实体的主键ID
	 * @return 查询结果
	 */
	ResultDO<BwlEnumDO> getById(Integer id);
	
	BwlEnumDO selectById(Integer id);
	
	BwlEnumDO selectOne(BwlEnumQuery query);

	/**
	 * 根据一组查询条件统计总数
	 * 
	 * @param query 查询条件
	 * @return 满足查询条件的记录总数
	 */
	int count(BwlEnumQuery query);
	
	/**
	 * 根据一组查询条件查询业务实体列表
	 * 
	 * @param query 查询条件
	 * @return 业务实体列表集合
	 */
	List<BwlEnumDO> findList(BwlEnumQuery query);
	
	/**
	 * 根据一组查询条件查询业务实体列表，同时返回总记录数
	 * 
	 * @param query 查询条件
	 * @return 查询结果（含总记录数）
	 */
	QueryResult<BwlEnumDO> findListWithCount(BwlEnumQuery query);
}
