/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)RoleMenuService.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.service;

import java.util.List;

import ${packagePrefix}.dataobject.RoleMenuDO;
import ${packagePrefix}.query.RoleMenuQuery;
import com.github.javaclub.sword.domain.QueryResult;
import com.github.javaclub.sword.domain.ResultDO;
import com.github.javaclub.sword.domain.dto.BatchOperationDTO;

/**
 * RoleMenuService
 *
 * @version $Id: RoleMenuService.java ${currentTime} Exp $
 */
public interface RoleMenuService {

	/**
	 * 创建或更新业务实体（RoleMenuDO）
	 * 
	 * @param roleMenuDO 业务实体
	 * @return 操作结果
	 */
	ResultDO<Boolean> save(RoleMenuDO roleMenuDO);

	/**
	 * 创建业务实体（RoleMenuDO）
	 * 
	 * @param roleMenuDO 业务实体
	 * @return 创建结果
	 */
	ResultDO<Boolean> create(RoleMenuDO roleMenuDO);
	
	/**
	 * 批量创建业务实体（RoleMenuDO）
	 * 
	 * @param list 业务实体列表集合
	 * @return 批量处理结果
	 */
	BatchOperationDTO<RoleMenuDO> createBatch(List<RoleMenuDO> list);
	
	/**
	 * 更新业务实体（RoleMenuDO）
	 * 
	 * @param roleMenuDO 业务实体
	 * @return 更新结果
	 */
	ResultDO<Boolean> update(RoleMenuDO roleMenuDO);
	
	/**
	 * 根据主键删除单个业务实体（RoleMenuDO）
	 * 
	 * @param id 业务实体的主键ID
	 * @return 删除结果
	 */
	ResultDO<Boolean> deleteById(Long id);
	
	/**
	 * 根据主键查询单个业务实体（RoleMenuDO）
	 * 
	 * @param id 业务实体的主键ID
	 * @return 查询结果
	 */
	ResultDO<RoleMenuDO> getById(Long id);
	
	RoleMenuDO selectById(Long id);
	
	RoleMenuDO selectOne(RoleMenuQuery query);
	
	List<Long> findRoleMenuNode(Long roleId);

	/**
	 * 根据一组查询条件统计总数
	 * 
	 * @param query 查询条件
	 * @return 满足查询条件的记录总数
	 */
	int count(RoleMenuQuery query);
	
	/**
	 * 根据一组查询条件查询业务实体列表
	 * 
	 * @param query 查询条件
	 * @return 业务实体列表集合
	 */
	List<RoleMenuDO> findList(RoleMenuQuery query);
	
	/**
	 * 根据一组查询条件查询业务实体列表，同时返回总记录数
	 * 
	 * @param query 查询条件
	 * @return 查询结果（含总记录数）
	 */
	QueryResult<RoleMenuDO> findListWithCount(RoleMenuQuery query);
}
