/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)RoleService.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${packagePrefix}.service;

import java.util.List;

import com.github.javaclub.sword.domain.QueryResult;
import com.github.javaclub.sword.domain.ResultDO;
import com.github.javaclub.sword.domain.dto.BatchOperationDTO;
import ${packagePrefix}.dataobject.RoleDO;
import ${packagePrefix}.query.RoleQuery;
import ${packagePrefix}.service.params.RoleParam;

/**
 * RoleService
 *
 * @version $Id: RoleService.java ${currentTime} Exp $
 */
public interface RoleService {
	
	
	ResultDO<Boolean> saveBatch(RoleParam param);

	/**
	 * 创建或更新业务实体（RoleDO）
	 * 
	 * @param roleDO 业务实体
	 * @return 操作结果
	 */
	ResultDO<Boolean> save(RoleDO roleDO);

	/**
	 * 创建业务实体（RoleDO）
	 * 
	 * @param roleDO 业务实体
	 * @return 创建结果
	 */
	ResultDO<Boolean> create(RoleDO roleDO);
	
	/**
	 * 批量创建业务实体（RoleDO）
	 * 
	 * @param list 业务实体列表集合
	 * @return 批量处理结果
	 */
	BatchOperationDTO<RoleDO> createBatch(List<RoleDO> list);
	
	/**
	 * 更新业务实体（RoleDO）
	 * 
	 * @param roleDO 业务实体
	 * @return 更新结果
	 */
	ResultDO<Boolean> update(RoleDO roleDO);
	
	/**
	 * 根据主键删除单个业务实体（RoleDO）
	 * 
	 * @param id 业务实体的主键ID
	 * @return 删除结果
	 */
	ResultDO<Boolean> deleteById(Long id);
	
	/**
	 * 根据主键查询单个业务实体（RoleDO）
	 * 
	 * @param id 业务实体的主键ID
	 * @return 查询结果
	 */
	ResultDO<RoleDO> getById(Long id);
	
	RoleDO selectById(Long id);
	
	RoleDO selectOne(RoleQuery query);

	/**
	 * 根据一组查询条件统计总数
	 * 
	 * @param query 查询条件
	 * @return 满足查询条件的记录总数
	 */
	int count(RoleQuery query);
	
	/**
	 * 根据一组查询条件查询业务实体列表
	 * 
	 * @param query 查询条件
	 * @return 业务实体列表集合
	 */
	List<RoleDO> findList(RoleQuery query);
	
	/**
	 * 根据一组查询条件查询业务实体列表，同时返回总记录数
	 * 
	 * @param query 查询条件
	 * @return 查询结果（含总记录数）
	 */
	QueryResult<RoleDO> findListWithCount(RoleQuery query);
	
	/**
	 * 查询用户所拥有的角色
	 *
	 * @param userId 用户账号ID
	 * @return
	 */
	List<RoleDO> findUserRoleList(Long userId);
}
