/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)MenuModuleController.java	${date}
 *
 * Copyright (c) ${year} - 2099. All Rights Reserved.
 *
 */

package ${packagePrefix}.web.admin;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import ${packagePrefix}.dataobject.MenuModuleDO;
import ${packagePrefix}.query.MenuModuleQuery;
import ${packagePrefix}.query.RoleMenuQuery;
import ${packagePrefix}.service.MenuModuleService;
import ${packagePrefix}.service.RoleMenuService;
import com.github.javaclub.sword.BizException;
import com.github.javaclub.sword.core.BizObjects;
import com.github.javaclub.sword.domain.QueryResult;
import com.github.javaclub.sword.domain.ResultDO;
import com.github.javaclub.sword.util.WebUtil;
import com.github.javaclub.sword.web.HttpResult;
import com.github.javaclub.sword.web.PageResultSet;
import com.google.common.collect.Maps;

/**
 * MenuModuleController
 *
 * @author <a href="mailto:gerald.chen.hz@gmail.com">Gerald Chen</a>
 * @version $Id: MenuModuleController.java ${currentTime} Exp $
 */
@RestController
@RequestMapping("/admin/menu")
public class MenuModuleController extends AdminControllerBase {
	
	static final Logger log = LoggerFactory.getLogger(MenuModuleController.class);
	
	@Autowired
	private MenuModuleService menuModuleService;
	
	@Autowired
	private RoleMenuService roleMenuService;
	
	@PostMapping(value = "/saveRequest")
	public HttpResult<Long> saveRequest(HttpServletRequest request) throws Exception {
		MenuModuleDO post = WebUtil.parseObject(request, MenuModuleDO.class);
		try {
			// validate check for MenuModuleDO
			 if(null == post.getId() || 0 >= post.getId()) {
            	post.setCreator(getLoginUsername());
            	post.setModifier(getLoginUsername());
            } else {
            	post.setModifier(getLoginUsername());
            }
		} catch (BizException e) {
			return HttpResult.failure(e.getMessage());
		}
		
		ResultDO<Boolean> r = menuModuleService.save(post);
        if(!r.isSuccess()) {
            return HttpResult.failure(r.getMessage());
        }
        
        return HttpResult.success(post.getId());
	}
	
	@GetMapping(value = "/detail")
	public HttpResult<MenuModuleDO> detail(Long id) {
		return doDetail(id);
	}
	
	@GetMapping(value = "/detail/{id}")
	public HttpResult<MenuModuleDO> _detail(@PathVariable Long id) {
		return doDetail(id);
	}
	
	@PostMapping(value = "/delete")
	public HttpResult<Boolean> delete(Long id) {
		return doDelete(id);
	}

	@PostMapping(value = "/delete/{id}")
	public HttpResult<Boolean> _delete(@PathVariable Long id) {
		return doDelete(id);
	}
	
	@GetMapping(value = "/pagelist")
	public HttpResult<PageResultSet<MenuModuleDO>> list(@RequestBody MenuModuleQuery request) {
		QueryResult<MenuModuleDO> queryResult = menuModuleService.findListWithCount(request);
		PageResultSet<MenuModuleDO> sets = new PageResultSet<>(request.getPageNo(), request.getPageSize());
		sets.setAllRow(queryResult.getTotalCount());
		sets.setList(queryResult.getEntry());
		return HttpResult.success(sets);
	}
	
	/**
	 * BootstrapTable Data Api
	 */
	@GetMapping(value = "/bootstrapTableList")
    public Map<String, Object> listData(HttpServletRequest request, Model model) {
		MenuModuleQuery query = WebUtil.parseObject(request, MenuModuleQuery.class);
		int count = menuModuleService.count(query);
		List<MenuModuleDO> list = menuModuleService.findList(query);
        Map<String, Object> map = Maps.newHashMap();
        map.put("rows", null == list ? new ArrayList<MenuModuleDO>() : list);
        map.put("total", count);
        return map;
    }
	
	@GetMapping(value = "/queryMaxSort")
    public HttpResult<Long> queryMaxSort(HttpServletRequest request, Model model) {
		MenuModuleQuery query = WebUtil.parseObject(request, MenuModuleQuery.class);
		Long sort = menuModuleService.queryMaxSort(query);
        return HttpResult.success(sort);
    }
	
	protected HttpResult<MenuModuleDO> doDetail(Long id) {
		ResultDO<MenuModuleDO> db = menuModuleService.getById(id);
		return HttpResult.success(db.getEntry());
	}
	
	protected HttpResult<Boolean> doDelete(Long id) {
		ResultDO<MenuModuleDO> db = menuModuleService.getById(id);
		if(!db.isSuccess() || null == db.getEntry()) { // 不存在
			return HttpResult.failure("节点不存在或已被删除");
		}
		List<MenuModuleDO> list = menuModuleService.findByParentId(id);
		if(BizObjects.length(list) > 0) {
			return HttpResult.failure("节点下存在子节点，不可删除！");
		}
		// 判断是否已经分配被某角色
		RoleMenuQuery query = new RoleMenuQuery();
		query.setMenuId(id);
		int rows = roleMenuService.count(query);
		if (rows > 0) {
			return HttpResult.failure("该菜单项处于使用状态，不可删除！");
		}
		ResultDO<Boolean> operate = menuModuleService.deleteById(id);
		if(!operate.isSuccess()) {
			return HttpResult.failure(operate.getMessage());
		}
		return HttpResult.success();
	}
	
}

