/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)ResourceController.java	${date}
 *
 * Copyright (c) ${year} - 2099. All Rights Reserved.
 *
 */

package ${packagePrefix}.web.admin;

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.github.javaclub.sword.web.HttpResult;

/**
 * ResourceController
 *
 * @author <a href="mailto:gerald.chen.hz@gmail.com">Gerald Chen</a>
 * @version $Id: ResourceController.java ${currentTime} Exp $
 */
@RestController
@RequestMapping("/admin/redis")
public class RedisMonitorController extends AdminControllerBase {
	
	static final Logger log = LoggerFactory.getLogger(RedisMonitorController.class);
	
	@GetMapping(value = "/keysize")
	public HttpResult<Map<String, Object>> keysize() throws Exception {
		Map<String, Object> map = redisCacheManager.getKeysSize();
		return HttpResult.success(map);
	}
	
	@GetMapping(value = "/memory")
	public HttpResult<Map<String, Object>> memory() throws Exception {
		Map<String, Object> map = redisCacheManager.getMemoryInfo();
		return HttpResult.success(map);
	}
	
}

