/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)ResourceController.java	${date}
 *
 * Copyright (c) ${year} - 2099. All Rights Reserved.
 *
 */

package ${packagePrefix}.web.admin;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import ${packagePrefix}.dataobject.ResourceDO;
import ${packagePrefix}.query.ResourceQuery;
import ${packagePrefix}.service.ResourceService;
import com.github.javaclub.sword.BizException;
import com.github.javaclub.sword.domain.QueryResult;
import com.github.javaclub.sword.domain.ResultDO;
import com.github.javaclub.sword.util.WebUtil;
import com.github.javaclub.sword.web.HttpResult;
import com.github.javaclub.sword.web.PageResultSet;
import com.google.common.collect.Maps;

/**
 * ResourceController
 *
 * @author <a href="mailto:gerald.chen.hz@gmail.com">Gerald Chen</a>
 * @version $Id: ResourceController.java ${currentTime} Exp $
 */
@RestController
@RequestMapping("/admin/resource")
public class ResourceController extends AdminControllerBase {
	
	static final Logger log = LoggerFactory.getLogger(ResourceController.class);
	
	@Autowired
	private ResourceService resourceService;
	
	@PostMapping(value = "/saveRequest")
	public HttpResult<Long> saveRequest(HttpServletRequest request) throws Exception {
		ResourceDO post = WebUtil.parseObject(request, ResourceDO.class);
		try {
			// validate check for ResourceDO
			 if(null == post.getId() || 0 >= post.getId()) {
            	post.setCreator(getLoginUsername());
            	post.setModifier(getLoginUsername());
            } else {
            	post.setModifier(getLoginUsername());
            }
		} catch (BizException e) {
			return HttpResult.failure(e.getMessage());
		}
		
		ResultDO<Boolean> r = resourceService.save(post);
        if(!r.isSuccess()) {
            return HttpResult.failure(r.getMessage());
        }
        
        return HttpResult.success(post.getId());
	}
	
	@GetMapping(value = "/detail")
	public HttpResult<ResourceDO> detail(Long id) {
		return doDetail(id);
	}
	
	@GetMapping(value = "/detail/{id}")
	public HttpResult<ResourceDO> _detail(@PathVariable Long id) {
		return doDetail(id);
	}

	@PostMapping(value = "/delete")
	public HttpResult<Boolean> delete(Long id) {
		return doDelete(id);
	}

	@PostMapping(value = "/delete/{id}")
	public HttpResult<Boolean> _delete(@PathVariable Long id) {
		return doDelete(id);
	}
	
	@GetMapping(value = "/pagelist")
	public HttpResult<PageResultSet<ResourceDO>> list(@RequestBody ResourceQuery request) {
		QueryResult<ResourceDO> queryResult = resourceService.findListWithCount(request);
		PageResultSet<ResourceDO> sets = new PageResultSet<>(request.getPageNo(), request.getPageSize());
		sets.setAllRow(queryResult.getTotalCount());
		sets.setList(queryResult.getEntry());
		return HttpResult.success(sets);
	}
	
	/**
	 * BootstrapTable Data Api
	 */
	@GetMapping(value = { "/bootstrapTableList", "/queryList" })
    public Map<String, Object> listData(HttpServletRequest request, Model model) {
		ResourceQuery query = WebUtil.parseObject(request, ResourceQuery.class);
		query.rebuildIds();
		int count = resourceService.count(query);
		List<ResourceDO> list = resourceService.findList(query);
        Map<String, Object> map = Maps.newHashMap();
        map.put("rows", null == list ? new ArrayList<ResourceDO>() : list);
        map.put("total", count);
        return map;
    }
	
	protected HttpResult<ResourceDO> doDetail(Long id) {
		ResultDO<ResourceDO> db = resourceService.getById(id);
		return HttpResult.success(db.getEntry());
	}
	
	protected HttpResult<Boolean> doDelete(Long id) {
		ResultDO<ResourceDO> db = resourceService.getById(id);
		if(!db.isSuccess() || null == db.getEntry()) { // 不存在
			return HttpResult.failure("数据不存在或已被删除");
		}
		ResultDO<Boolean> operate = resourceService.deleteById(id);
		if(!operate.isSuccess()) {
			return HttpResult.failure(operate.getMessage());
		}
		return HttpResult.success();
	}
	
}

