/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)${Entity}Controller.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${controllerPackage};

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import ${entityPackage}.${Entity}DO;
import ${entityQueryPackage}.${Entity}Query;
import ${serviceApiPackage}.${Entity}Service;
import com.github.javaclub.sword.domain.QueryResult;
import com.github.javaclub.sword.domain.ResultDO;
import com.github.javaclub.sword.web.HttpResult;
import com.github.javaclub.sword.web.PageResultSet;

/**
 * ${Entity}Controller
 *
 * @author <a href="mailto:gerald.chen.hz@gmail.com">Gerald Chen</a>
 * @version $Id: ${Entity}Controller.java 2017年6月14日 18:03:58 Exp $
 */
@Controller
@RequestMapping("/api/${full_lower_entity}")
public class ${Entity}Controller {
	
	static final Logger log = LoggerFactory.getLogger(${Entity}Controller.class);
	
	@Autowired
	private ${Entity}Service ${entity}Service;
	
	@RequestMapping(value = "/save", method = RequestMethod.POST)
	@ResponseBody
	public HttpResult save(@RequestBody ${Entity}DO post) {
		ResultDO<Boolean> operate = ${entity}Service.save(post);
		return HttpResult.result(operate.isSuccess(), operate.isSuccess() ? post.getId() : operate.getMessage());
	}
	
	@RequestMapping(value = "/detail", method = RequestMethod.GET)
	@ResponseBody
	public HttpResult detail(Long id) {
		return doDetail(id);
	}
	
	@RequestMapping(value = "/detail/{id}", method = RequestMethod.GET)
	@ResponseBody
	public HttpResult _detail(@PathVariable Long id) {
		return doDetail(id);
	}

	@RequestMapping(value = "/delete", method = RequestMethod.POST)
	@ResponseBody
	public HttpResult delete(Long id) {
		return doDelete(id);
	}

	@RequestMapping(value = "/delete/{id}", method = RequestMethod.POST)
	@ResponseBody
	public HttpResult _delete(@PathVariable Long id) {
		return doDelete(id);
	}
	
	@RequestMapping(value = "/list", method = RequestMethod.GET)
	@ResponseBody
	public HttpResult list(@RequestBody ${Entity}Query request) {
		QueryResult<${Entity}DO> queryResult = ${entity}Service.findListWithCount(request);
		PageResultSet<${Entity}DO> sets = new PageResultSet<>(request.getPageNo(), request.getPageSize());
		sets.setAllRow(queryResult.getTotalCount());
		sets.setList(queryResult.getEntry());
		return HttpResult.success(sets);
	}
	
	protected HttpResult doDetail(Long id) {
		ResultDO<${Entity}DO> db = ${entity}Service.getById(id);
		return HttpResult.success(db.getEntry());
	}
	
	protected HttpResult doDelete(Long id) {
		ResultDO<${Entity}DO> db = ${entity}Service.getById(id);
		if(!db.isSuccess() || null == db.getEntry()) { // 不存在
			return HttpResult.failure("数据不存在或已被删除");
		}
		ResultDO<Boolean> operate = ${entity}Service.deleteById(id);
		if(!operate.isSuccess()) {
			return HttpResult.failure(operate.getMessage());
		}
		return HttpResult.success();
	}
	
}
