/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)${Entity}DAO.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${daoPackage};

import com.github.javaclub.sword.domain.StandardDAO;
import ${entityPackage}.${Entity}DO;

/**
 * ${Entity}DAO
 *
 * @version $Id: ${Entity}DAO.java ${datetime} Exp $
 */
public interface ${Entity}DAO extends StandardDAO<${Entity}DO> {
	
	
	
}

