/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)${Entity}DO.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${entityPackage};

import com.github.javaclub.sword.domain.BaseDO;

/**
 * ${Entity}DO
 *
 * @version $Id: ${Entity}DO.java ${datetime} Exp $
 */
public class ${Entity}DO extends BaseDO {

	private static final long serialVersionUID = 1L;
	
${entityFields}

	public ${Entity}DO() {
	}

${entityGetSetMethods}
	
}

