/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)${Entity}Query.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${entityQueryPackage};


import ${baseQueryFullClass};

/**
 * ${Entity}Query
 *
 * @version $Id: ${Entity}Query.java ${datetime} Exp $
 */
public class ${Entity}Query extends ${baseQueryClassName} {

	private static final long serialVersionUID = 1L;
	
	${eq_query}${in_query}${notin_query}${like_query}${notlike_query}

	public ${Entity}Query() {
	}
	
	${getter_setter}
	
}

