/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)${Entity}${daoSuffix}.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${daoPackage};

import ${baseDaoFullClass};
import ${entityPackage}.${Entity}${entitySuffix};

/**
 * ${Entity}${daoSuffix}
 *
 * @version $Id: ${Entity}${daoSuffix}.java ${datetime} Exp $
 */
public interface ${Entity}${daoSuffix} extends ${baseDaoClassName}<${Entity}${entitySuffix}, ${pkClass}> {
	
	
	
}

