/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)${Entity}Query.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${entityQueryPackage};


import java.util.List;

import ${baseQueryFullClass};

/**
 * ${Entity}Query
 *
 * @version $Id: ${Entity}Query.java ${datetime} Exp $
 */
public class ${Entity}Query extends ${baseQueryClassName} {

	private static final long serialVersionUID = ${serialVersionUID}L;
	
	/**
	 * 根据主键查询 
	 */
	private ${pkClass} id;
	
	/**
	 * 根据主键ID列表批量查询 
	 */
	private List<${pkClass}> ids; 
	
	/**
	 * 最小ID过滤条件 
	 */
	private ${pkClass} minId;
	
	/**
	 * 最大ID过滤条件 
	 */
	private ${pkClass} maxId;
	
	${eq_query}${in_query}${notin_query}${like_query}${notlike_query}

	public ${Entity}Query() {
	}
	
	public ${pkClass} getId() {
		return id;
	}

	public void setId(${pkClass} id) {
		this.id = id;
	}

	public List<${pkClass}> getIds() {
		return ids;
	}

	public void setIds(List<${pkClass}> ids) {
		this.ids = ids;
	}
	
	public ${pkClass} getMinId() {
		return minId;
	}

	public void setMinId(${pkClass} minId) {
		this.minId = minId;
	}
	
	public ${pkClass} getMaxId() {
		return maxId;
	}

	public void setMaxId(${pkClass} maxId) {
		this.maxId = maxId;
	}
	
	${getter_setter}
	
}

