/* Automatic generated by CrudCodeGenerator wirtten by Gerald Chen
 *
 * @(#)${Entity}${entitySuffix}.java	${date}
 *
 * Copyright (c) ${year}. All Rights Reserved.
 *
 */

package ${entityPackage};

import ${baseEntityFullClass};

/**
 * ${Entity}${entitySuffix}
 *
 * @version $Id: ${Entity}${entitySuffix}.java ${datetime} Exp $
 */
public class ${Entity}${entitySuffix} extends ${baseEntityClassName} {

	private static final long serialVersionUID = ${serialVersionUID}L;
	
${entityFields}

	public ${Entity}${entitySuffix}() {
	}

${entityGetSetMethods}
	
}

